services:
  - type: web
    name: sign-ai-backend
    env: python
    region: singapore     # หรือ singapore / singapore-1 ทำงานเร็วสุดสำหรับไทย

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000

    plan: free

    envVars:
      - key: PYTHON_VERSION
        value: 3.11

    disk:
      name: dataset-storage
      mountPath: /opt/render/project/src/dataset
      sizeGB: 5

    autoDeploy: true
